rental_mobil/routes/web.php
<?php

Route::name('customer.')->group(function(){
    Route::get('/', 'CustomerController@index')->name('index');
    Route::get('/mobil', 'CustomerController@mobil')->name('mobil');
    Route::get('/mobil/{mobil}', 'CustomerController@details')->name('customer.details');
    
    Route::middleware(['auth'])->group(function(){
        Route::get('/rental/{mobil}', 'CustomerController@rental')->name('customer.rental');
        Route::post('/transaksi/{mobil}', 'CustomerController@transaksi')->name('customer.transaksi');
        Route::get('/daftar', 'CustomerController@daftar')->name('customer.daftar');
        Route::get('/checkout/{transaksi}', 'CustomerController@checkout')->name('customer.checkout');
        Route::get('/pembayaran/{transaksi}', 'CustomerController@pembayaran')->name('customer.pembayaran');
        Route::post('/upload/{transaksi}', 'CustomerController@upload')->name('customer.upload');
        Route::get('/print/{transaksi}', 'CustomerController@print')->name('customer.print');
        
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('/dashboard/profile', 'DashboardController@profile')->name('profile');
        Route::put('/dashboard', 'DashboardController@update')->name('update');
        Route::get('/dashboard/transaksi', 'DashboardController@transaksi')->name('transaksi');
    });
});

Auth::routes();

Route::middleware(['web','auth', 'admin'])
    ->namespace('Admin')
    ->prefix('admin')
    ->name('admin.')
    ->group(function(){
        Route::get('/', 'DashboardController@index')->name('dashboard.index');
        
        Route::resource('user', 'UserController');
        Route::get('/profile', 'ProfileController@index')->name('profile.index');
        Route::put('/profile/update', 'ProfileController@update')->name('profile.update');

        Route::resource('mobil','MobilController');
        Route::resource('merk','MerkController');
        Route::get('/mobil/{{$value->id}}','MobilController@show');
        Route::get('/mobil/{{$value->id}}/edit','MobilController@edit');
        Route::put('/mobil/{{$value->id}}','MobilController@update');
        Route::post('/merklist','MerKController@storemerk')->name('merk.storemerk');
        Route::delete('/mobil/{{$value->id}}','MobilController@destroy');
        Route::delete('/merk/{{$value->id}}','MobilController@destroy');

        Route::get('/transaksi/{transaksi}/aksi', 'TransaksiController@aksi')->name('transaksi.aksi');
        Route::resource('/transaksi', 'TransaksiController');
      
        Route::get('/pembayaran/{transaksi}', 'PembayaranController@show')->name('pembayaran.show');
        Route::put('/pembayaran/{transaksi}', 'PembayaranController@update')->name('pembayaran.update');
        Route::get('/pembayaran/{transaksi}/download', 'PembayaranController@download')->name('pembayaran.download');

    });

rental_mobil/app/Pembayaran.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pembayaran extends Model
{
    protected $table = 'pembayaran';

    protected $fillable = ['status_pembayaran'];

    public $timestamps = false;

    public function transaksi() 
    {
        return $this->belongsTo('App\Trasansaksi');
    }
}

rental_mobil/app/Http/Controllers/Admin/PembayaranController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Pembayaran;

class PembayaranController extends Controller
{
    public function show($transaksi_id)
    {
        $pembayaran = DB::table('pembayaran')
                ->where('transaksi_id', '=', $transaksi_id)
                ->get();

        return view('admin.pages.pembayaran.details', compact('pembayaran'));
    }

    public function update($id, Request $request)
    {
        $pembayaran = Pembayaran::findOrfail($id);
        $input = $request->all();
        $pembayaran->update($input);
        return redirect('admin/transaksi');
    }

    public function download($id)
    {
        $pembayaran = Pembayaran::findOrfail($id);
        $file = public_path(). "/bukti_pembayaran/" .$pembayaran->bukti_pembayaran;
        return response()->download($file);
    }
}

rental_mobil/resources/views/admin/pages/pembayaran/details.blade.php
@extends('admin.layouts.master')

@section('title')
    Detail Pembayaran
@endsection

@section('content')
    <div class="card">
        <table class="table">
            <tr>
                @foreach ($pembayaran as $pmb)
                <td class="bold">ID</td><td>{{$pmb->id}}</td>
            </tr>
            <tr>
                <td>Bukti Pembayaran</td>
                <td>
                    <a href="{{route('admin.pembayaran.download',$pmb->id)}}" class="btn btn-sm btn-info"">
                        <i class="fas fa-download"> Download Bukti Pembayaran</i>
                    </a>
                </td>
            </tr>
            <tr>
                <td>Status Pembayaran</td>
                <td>
                    @if ($pmb->status_pembayaran == 0)
                    <span class="badge badge-danger">Menunggu Pembayaran</span>    
                    @elseif ($pmb->status_pembayaran == 1)
                    <span class="badge badge-info">Menunggu Konfirmasi</span>
                    @elseif ($pmb->status_pembayaran == 2)
                    <span class="badge badge-success">Terkonfirmasi</span>
                    @endif    
                </td>
            </tr>        
        </table>
        <form class="mr-4 ml-4 mb-4 mt-0"action="{{route('admin.pembayaran.update',$pmb->id)}}" method="POST">
            @csrf
            @method('PUT')
            <div class="form-group">
                <input type="text" class="form-control" name="status_pembayaran" value="2" id="status_pembayaran" hidden>
            </div>
            <button type="submit" class="btn btn-primary">Konfirmasi Pembayaran</button>
        </form>
        @endforeach
    </div>
@endsection

rental_mobil/resources/views/admin/pages/pembayaran/index.blade.php
@extends('admin.layouts.master')

@section('title')
    Daftar Pembayaran
@endsection

@section('content')
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">No.</th>
            <th scope="col">Id Transaksi</th>
            <th scope="col">Bukti Pembayaran</th>
            <th scope="col">Status Pembayaran</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
            {{-- @forelse ($cast as $key=>$value)
                <tr>
                    <td>{{$key + 1}}</th>
                    <td>{{$value->nama}}</td>
                    <td>{{$value->umur}}</td>
                    <td>{{$value->bio}}</td>
                    <td>
                        <a href="/cast/{{$value->id}}" class="btn btn-info">Show</a>
                        <a href="/cast/{{$value->id}}/edit" class="btn btn-primary">Edit</a>
                        <form action="/cast/{{$value->id}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <input type="submit" class="btn btn-danger my-1" value="Delete">
                        </form>
                    </td>
                </tr>
            @empty
                <tr colspan="5">
                    <td class>No data</td>
                </tr>  
            @endforelse               --}}
        </tbody>
    </table>
@endsection