rental_mobil/routes/web.php
<?php

Route::name('customer.')->group(function(){
    Route::get('/', 'CustomerController@index')->name('index');
    Route::get('/mobil', 'CustomerController@mobil')->name('mobil');
    Route::get('/mobil/{mobil}', 'CustomerController@details')->name('customer.details');
    
    Route::middleware(['auth'])->group(function(){
        Route::get('/rental/{mobil}', 'CustomerController@rental')->name('customer.rental');
        Route::post('/transaksi/{mobil}', 'CustomerController@transaksi')->name('customer.transaksi');
        Route::get('/daftar', 'CustomerController@daftar')->name('customer.daftar');
        Route::get('/checkout/{transaksi}', 'CustomerController@checkout')->name('customer.checkout');
        Route::get('/pembayaran/{transaksi}', 'CustomerController@pembayaran')->name('customer.pembayaran');
        Route::post('/upload/{transaksi}', 'CustomerController@upload')->name('customer.upload');
        Route::get('/print/{transaksi}', 'CustomerController@print')->name('customer.print');
        
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('/dashboard/profile', 'DashboardController@profile')->name('profile');
        Route::put('/dashboard', 'DashboardController@update')->name('update');
        Route::get('/dashboard/transaksi', 'DashboardController@transaksi')->name('transaksi');
    });
});

Auth::routes();

Route::middleware(['web','auth', 'admin'])
    ->namespace('Admin')
    ->prefix('admin')
    ->name('admin.')
    ->group(function(){
        Route::get('/', 'DashboardController@index')->name('dashboard.index');
        
        Route::resource('user', 'UserController');
        Route::get('/profile', 'ProfileController@index')->name('profile.index');
        Route::put('/profile/update', 'ProfileController@update')->name('profile.update');

        Route::resource('mobil','MobilController');
        Route::resource('merk','MerkController');
        Route::get('/mobil/{{$value->id}}','MobilController@show');
        Route::get('/mobil/{{$value->id}}/edit','MobilController@edit');
        Route::put('/mobil/{{$value->id}}','MobilController@update');
        Route::post('/merklist','MerKController@storemerk')->name('merk.storemerk');
        Route::delete('/mobil/{{$value->id}}','MobilController@destroy');
        Route::delete('/merk/{{$value->id}}','MobilController@destroy');

        Route::get('/transaksi/{transaksi}/aksi', 'TransaksiController@aksi')->name('transaksi.aksi');
        Route::resource('/transaksi', 'TransaksiController');
      
        Route::get('/pembayaran/{transaksi}', 'PembayaranController@show')->name('pembayaran.show');
        Route::put('/pembayaran/{transaksi}', 'PembayaranController@update')->name('pembayaran.update');
        Route::get('/pembayaran/{transaksi}/download', 'PembayaranController@download')->name('pembayaran.download');

    });

rental_mobil/app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Transaksi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;

class CustomerController extends Controller
{
    public function index(){
        return view('customer.pages.index');
    }

    public function mobil()
    {
        $mobil = DB::table('mobil')
                ->join('merk_mobil', 'mobil.merk_mobil_id', '=', 'merk_mobil.id')
                ->get();
        return view('customer.pages.mobil', compact('mobil'));
    }

    public function details($id)
    {
        $mobil = DB::table('mobil')
                ->join('merk_mobil', 'mobil.merk_mobil_id', '=', 'merk_mobil.id')
                ->where('mobil.id', '=', $id)
                ->get();
        return view('customer.pages.details', compact('mobil'));
    }

    public function rental($id)
    {
        $user = Auth::user()->id;
        $mobil = DB::table('mobil')
                ->join('merk_mobil', 'mobil.merk_mobil_id', '=', 'merk_mobil.id')
                ->where('mobil.id', '=', $id)
                ->get();
        return view('customer.pages.rental', compact('mobil', 'user'));
    }

    public function transaksi($id, Request $request)
    {
        $request->validate([
            'tanggal_rental' => 'required',
            'tanggal_kembali' => 'required',
            'harga' => 'required',
            'denda' => 'required',
            'users_id' => 'required',
        ]);

        $x = strtotime($request["tanggal_kembali"]);
        $y = strtotime($request["tanggal_rental"]);
        $durasi_rental = abs($x - $y)/(60*60*24);
        $total_pembayaran = $request['harga'] * $durasi_rental;
        $status_pengembalian = 0;
        $status_transaksi = 0;
        $mobil_id = $id;

        $query = DB::table('transaksi')->insert([
            "tanggal_rental" => $request["tanggal_rental"],
            "tanggal_kembali" => $request["tanggal_kembali"],
            "harga" => $request["harga"],
            "denda" => $request["denda"],
            "users_id" => $request["users_id"],
            "mobil_id" => $mobil_id,
            "durasi_rental" => $durasi_rental,
            "total_pembayaran" => $total_pembayaran,
            "status_pengembalian" => $status_pengembalian,
            "status_transaksi" => $status_transaksi,
        ]);
 
        return redirect('/daftar');
    }

    public function daftar() 
    {
        $user = Auth::user()->id;
        $mobil = DB::table('mobil')
                ->join('merk_mobil', 'mobil.merk_mobil_id', '=', 'merk_mobil.id')
                ->join('transaksi', 'mobil.id', '=', 'transaksi.mobil_id')
                ->where('transaksi.users_id', '=', $user)
                ->select('merk_mobil.nama', 'mobil.no_plat', 'transaksi.total_pembayaran', 'transaksi.status_transaksi', 'transaksi.status_pengembalian', 'transaksi.id')
                ->get();
        
        return view('customer.pages.daftar', compact('mobil', 'user'));
    }

    public function checkout($id) 
    {
        DB::table('transaksi')
        ->join('mobil', 'transaksi.mobil_id', '=', 'mobil.id')
        ->where('transaksi.id', '=', $id)
        ->update([
            'status_transaksi' => 1,
            'status' => 1,
            ]);

        DB::table('pembayaran')->insert([
            "status_pembayaran" => 0,
            "bukti_pembayaran" => '-',
            "transaksi_id" => $id,
        ]); 

        $user = Auth::user()->id;
        
        $mobil = DB::table('mobil')
                ->join('merk_mobil', 'mobil.merk_mobil_id', '=', 'merk_mobil.id')
                ->join('transaksi', 'mobil.id', '=', 'transaksi.mobil_id')
                ->where('transaksi.users_id', '=', $user)
                ->select('merk_mobil.nama', 'mobil.no_plat', 'transaksi.total_pembayaran', 'transaksi.status_transaksi', 'transaksi.status_pengembalian', 'transaksi.id')
                ->get();
        
        return view('customer.pages.daftar', compact('mobil'));
    }

    public function pembayaran($id)
    {
        $user = Auth::user()->id;
        $mobil = DB::table('mobil')
                ->join('merk_mobil', 'mobil.merk_mobil_id', '=', 'merk_mobil.id')
                ->join('transaksi', 'mobil.id', '=', 'transaksi.mobil_id')
                ->join('pembayaran', 'transaksi.id', '=', 'pembayaran.transaksi_id')
                ->where('transaksi.users_id', '=', $user)
                ->select('merk_mobil.nama', 'mobil.no_plat', 'transaksi.total_pembayaran', 'transaksi.status_transaksi', 'transaksi.status_pengembalian', 'transaksi.id', 'transaksi.tanggal_rental', 'transaksi.tanggal_kembali', 'transaksi.harga', 'transaksi.durasi_rental', 'transaksi.total_pembayaran', 'pembayaran.status_pembayaran')
                ->get();
        
        return view('customer.pages.pembayaran', compact('mobil'));
    }

    public function upload($id, Request $request) {
        
        $request->validate([
			'bukti_pembayaran' => 'required',
		]);

        $file = $request->file('bukti_pembayaran');

        $name = 'Bukti_Pembayaran_' . $id. '.jpg'; 

        $tujuan_upload = public_path(). "/bukti_pembayaran";

        $file->move($tujuan_upload,$name);

        DB::table('pembayaran')
        ->where('transaksi_id', '=', $id)
        ->update([
            'bukti_pembayaran' => $name,
            'status_pembayaran' => 1,
            ]);
            
        $user = Auth::user()->id;
        $mobil = DB::table('mobil')
                ->join('merk_mobil', 'mobil.merk_mobil_id', '=', 'merk_mobil.id')
                ->join('transaksi', 'mobil.id', '=', 'transaksi.mobil_id')
                ->where('transaksi.users_id', '=', $user)
                ->select('merk_mobil.nama', 'mobil.no_plat', 'transaksi.total_pembayaran', 'transaksi.status_transaksi', 'transaksi.status_pengembalian', 'transaksi.id')
                ->get();
        
        return view('customer.pages.daftar', compact('user', 'mobil'));
    }

    public function print($id)
    {
        $user = Auth::user()->id;
        $transaksi = DB::table('mobil')
                ->join('merk_mobil', 'mobil.merk_mobil_id', '=', 'merk_mobil.id')
                ->join('transaksi', 'mobil.id', '=', 'transaksi.mobil_id')
                ->join('pembayaran', 'transaksi.id', '=', 'pembayaran.transaksi_id')
                ->where('transaksi.users_id', '=', $user)
                ->select('merk_mobil.nama', 'mobil.no_plat', 'transaksi.total_pembayaran', 'transaksi.status_transaksi', 'transaksi.status_pengembalian', 'transaksi.id', 'transaksi.tanggal_rental', 'transaksi.tanggal_kembali', 'transaksi.harga', 'transaksi.durasi_rental', 'transaksi.total_pembayaran', 'pembayaran.status_pembayaran')
                ->get();
        
        return view('customer.pages.cetak_invoice', compact('user', 'transaksi'));
    }
}

rental_mobil/resources/views/customer/partial/footer.blade.php
<footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="copyright-text">
            <p>
              Copyright © 2020 Company Name
              | Template by: <a href="https://www.phpjabbers.com/">PHPJabbers.com</a>
            </p>
          </div>
        </div>
      </div>
    </div>
</footer>

rental_mobil/resources/views/customer/partial/header.blade.php
<!-- Header -->
<header class="">
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        <a class="navbar-brand" href="{{route('customer.index')}}"><h2>Aplikasi Rental Mobil</h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{route('customer.index')}}">Beranda
                <span class="sr-only">(current)</span>
              </a>
            </li> 
            <li class="nav-item">
              <a class="nav-link" href="{{route('customer.mobil')}}">Mobil</a>
            </li>
            @auth
            <li class="nav-item">
              <a class="nav-link" href="/daftar">Transaksi</a>
            </li>
            <li class="nav-item">
                @if (Auth::user()->role === 'admin')
                <a class="nav-link" href="{{route('admin.dashboard.index')}}">Dashboard</a>   
                @else    
                <a class="nav-link" href="{{route('customer.dashboard')}}">Dashboard</a>
                @endif
            </li>
            @else
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">Login</a>
              </li>
            @endauth
          </ul>
        </div>
      </div>
    </nav>
</header>

rental_mobil/resources/views/customer/partial/script.blade.php
<!-- Bootstrap core JavaScript -->
<script src="{{asset('templates/assets/vendor/jquery/jquery.min.js')}}"></script>
<script src="{{asset('templates/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

<!-- Additional Scripts -->
<script src="{{asset('templates/assets/js/custom_customer.js')}}"></script>
<script src="{{asset('templates/assets/js/owl.js')}}"></script>
<script src="{{asset('templates/assets/js/slick.js')}}"></script>
<script src="{{asset('templates/assets/js/isotope.js')}}"></script>
<script src="{{asset('templates/assets/js/accordions.js')}}"></script>

<script language = "text/Javascript"> 
  cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
  function clearField(t){                   //declaring the array outside of the
  if(! cleared[t.id]){                      // function makes it static and global
      cleared[t.id] = 1;  // you could use true and false, but that's more typing
      t.value='';         // with more chance of typos
      t.style.color='#fff';
      }
  }
</script>

rental_mobil/resources/views/customer/partial/style.blade.php
<!-- Bootstrap core CSS -->
<link href="{{asset('templates/assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">

<!-- Additional CSS Files -->
<link rel="stylesheet" href="{{asset('templates/assets/css/fontawesome.css')}}">
<link rel="stylesheet" href="{{asset('templates/assets/css/style_customer.css')}}">
<link rel="stylesheet" href="{{asset('templates/assets/css/owl.css')}}">