rental_mobil/routes/web.php
<?php

Route::name('customer.')->group(function(){
    Route::get('/', 'CustomerController@index')->name('index');
    Route::get('/mobil', 'CustomerController@mobil')->name('mobil');
    Route::get('/mobil/{mobil}', 'CustomerController@details')->name('customer.details');
    
    Route::middleware(['auth'])->group(function(){
        Route::get('/rental/{mobil}', 'CustomerController@rental')->name('customer.rental');
        Route::post('/transaksi/{mobil}', 'CustomerController@transaksi')->name('customer.transaksi');
        Route::get('/daftar', 'CustomerController@daftar')->name('customer.daftar');
        Route::get('/checkout/{transaksi}', 'CustomerController@checkout')->name('customer.checkout');
        Route::get('/pembayaran/{transaksi}', 'CustomerController@pembayaran')->name('customer.pembayaran');
        Route::post('/upload/{transaksi}', 'CustomerController@upload')->name('customer.upload');
        Route::get('/print/{transaksi}', 'CustomerController@print')->name('customer.print');
        
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('/dashboard/profile', 'DashboardController@profile')->name('profile');
        Route::put('/dashboard', 'DashboardController@update')->name('update');
        Route::get('/dashboard/transaksi', 'DashboardController@transaksi')->name('transaksi');
    });
});

Auth::routes();

Route::middleware(['web','auth', 'admin'])
    ->namespace('Admin')
    ->prefix('admin')
    ->name('admin.')
    ->group(function(){
        Route::get('/', 'DashboardController@index')->name('dashboard.index');
        
        Route::resource('user', 'UserController');
        Route::get('/profile', 'ProfileController@index')->name('profile.index');
        Route::put('/profile/update', 'ProfileController@update')->name('profile.update');

        Route::resource('mobil','MobilController');
        Route::resource('merk','MerkController');
        Route::get('/mobil/{{$value->id}}','MobilController@show');
        Route::get('/mobil/{{$value->id}}/edit','MobilController@edit');
        Route::put('/mobil/{{$value->id}}','MobilController@update');
        Route::post('/merklist','MerKController@storemerk')->name('merk.storemerk');
        Route::delete('/mobil/{{$value->id}}','MobilController@destroy');
        Route::delete('/merk/{{$value->id}}','MobilController@destroy');

        Route::get('/transaksi/{transaksi}/aksi', 'TransaksiController@aksi')->name('transaksi.aksi');
        Route::resource('/transaksi', 'TransaksiController');
      
        Route::get('/pembayaran/{transaksi}', 'PembayaranController@show')->name('pembayaran.show');
        Route::put('/pembayaran/{transaksi}', 'PembayaranController@update')->name('pembayaran.update');
        Route::get('/pembayaran/{transaksi}/download', 'PembayaranController@download')->name('pembayaran.download');

    });

rental_mobil/resources/views/admin/partial/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
      Copyright &copy; 2018 <div class="bullet"></div> Design By <a href="https://nauval.in/">Muhamad Nauval Azhar</a>
    </div>
    <div class="footer-right">
      2.3.0
    </div>
  </footer>

rental_mobil/resources/views/admin/partial/navbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
      <ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
      </ul>
    </form>
    <ul class="navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{asset('templates/assets/img/avatar/avatar-1.png')}}" class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">{{Auth::user()->name}}</div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="{{route('customer.index')}}" class="dropdown-item has-icon text-primary"><i class="fas fa-home"></i>Home</a>
                <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
            </div>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </li>
    </ul>
</nav>

rental_mobil/resources/views/admin/partial/notification.blade.php
<script>
    @if (session('notif'))
        $.notify({
            message: '{{session('notif')}}' 
        },{
            
            type: 'success'
        });
    @endif
</script>

rental_mobil/resources/views/admin/partial/script.blade.php
<!-- General JS Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="{{asset('templates/assets/js/stisla.js')}}"></script>

<!-- JS Libraies --> 
<script src="{{asset('templates/assets/vendor/sweetalert2/sweetalert2.min.js')}}"></script>
<script src="{{asset('templates/assets/vendor/bsnotify/bootstrap-notify.min.js')}}"></script>
<!-- Template JS File -->
<script src="{{asset('templates/assets/js/scripts.js')}}"></script>
<script src="{{asset('templates/assets/js/custom.js')}}"></script>

<!-- Page Specific JS File -->
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.11.2/datatables.min.js"></script>

rental_mobil/resources/views/admin/partial/sidebar.blade.php
<aside id="sidebar-wrapper">
    <div class="sidebar-brand">
      <a href="index.html">RENTAL MOBIL</a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
      <a href="index.html">RM</a>
    </div>
    <ul class="sidebar-menu">
        <li class="menu-header">Menu</li>
        <li class="nav-item dropdown {{request()->routeIs('admin.dashboard.index') ? 'active' : ''}}">
          <a href="{{route('admin.dashboard.index')}}" class="nav-link"><i class="fas fa-fire"></i><span>Dashboard</span></a>
        </li>
        <li class="nav-item dropdown {{request()->routeIs('admin.merk*') ? 'active' : ''}}">
          <a href="{{route('admin.merk.index')}}" class="nav-link"><i class="fas fa-clipboard-list"></i><span>Merk Mobil</span></a>
        </li>
        <li class="nav-item dropdown {{request()->routeIs('admin.mobil*') ? 'active' : ''}}">
          <a href="{{route('admin.mobil.index')}}" class="nav-link"><i class="fas fa-car"></i><span>Daftar Mobil</span></a>
        </li>
        <li class="nav-item dropdown {{request()->routeIs('admin.transaksi*') ? 'active' : ''}}">
          <a href="{{route('admin.transaksi.index')}}" class="nav-link"><i class="fas fa-money-check"></i><span>Daftar Transaksi</span></a>
        </li>
        <li class="nav-item dropdown {{request()->routeIs('admin.user*') ? 'active' : ''}}">
          <a href="{{route('admin.user.index')}}" class="nav-link"><i class="fas fa-users"></i><span>Daftar User</span></a>
        </li>
        <li class="nav-item dropdown {{request()->routeIs('admin.profile*') ? 'active' : ''}}">
          <a href="{{route('admin.profile.index')}}" class="nav-link"><i class="fas fa-user"></i><span>Profil</span></a>
        </li>
    </ul>
</aside>

rental_mobil/resources/views/admin/partial/style.blade.php
<!-- General CSS Files -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<!-- CSS Libraries -->
<link rel="stylesheet" href="{{asset('templates/assets/vendor/sweetalert2/sweetalert2.min.css')}}">
<!-- Template CSS -->
<link rel="stylesheet" href="{{asset('templates/assets/css/style.css')}}">
<link rel="stylesheet" href="{{asset('templates/assets/css/components.css')}}">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.2/datatables.min.css"/>