rental_mobil/routes/web.php
<?php

Route::name('customer.')->group(function(){
    Route::get('/', 'CustomerController@index')->name('index');
    Route::get('/mobil', 'CustomerController@mobil')->name('mobil');
    Route::get('/mobil/{mobil}', 'CustomerController@details')->name('customer.details');
    
    Route::middleware(['auth'])->group(function(){
        Route::get('/rental/{mobil}', 'CustomerController@rental')->name('customer.rental');
        Route::post('/transaksi/{mobil}', 'CustomerController@transaksi')->name('customer.transaksi');
        Route::get('/daftar', 'CustomerController@daftar')->name('customer.daftar');
        Route::get('/checkout/{transaksi}', 'CustomerController@checkout')->name('customer.checkout');
        Route::get('/pembayaran/{transaksi}', 'CustomerController@pembayaran')->name('customer.pembayaran');
        Route::post('/upload/{transaksi}', 'CustomerController@upload')->name('customer.upload');
        Route::get('/print/{transaksi}', 'CustomerController@print')->name('customer.print');
        
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('/dashboard/profile', 'DashboardController@profile')->name('profile');
        Route::put('/dashboard', 'DashboardController@update')->name('update');
        Route::get('/dashboard/transaksi', 'DashboardController@transaksi')->name('transaksi');
    });
});

Auth::routes();

Route::middleware(['web','auth', 'admin'])
    ->namespace('Admin')
    ->prefix('admin')
    ->name('admin.')
    ->group(function(){
        Route::get('/', 'DashboardController@index')->name('dashboard.index');
        
        Route::resource('user', 'UserController');
        Route::get('/profile', 'ProfileController@index')->name('profile.index');
        Route::put('/profile/update', 'ProfileController@update')->name('profile.update');

        Route::resource('mobil','MobilController');
        Route::resource('merk','MerkController');
        Route::get('/mobil/{{$value->id}}','MobilController@show');
        Route::get('/mobil/{{$value->id}}/edit','MobilController@edit');
        Route::put('/mobil/{{$value->id}}','MobilController@update');
        Route::post('/merklist','MerKController@storemerk')->name('merk.storemerk');
        Route::delete('/mobil/{{$value->id}}','MobilController@destroy');
        Route::delete('/merk/{{$value->id}}','MobilController@destroy');

        Route::get('/transaksi/{transaksi}/aksi', 'TransaksiController@aksi')->name('transaksi.aksi');
        Route::resource('/transaksi', 'TransaksiController');
      
        Route::get('/pembayaran/{transaksi}', 'PembayaranController@show')->name('pembayaran.show');
        Route::put('/pembayaran/{transaksi}', 'PembayaranController@update')->name('pembayaran.update');
        Route::get('/pembayaran/{transaksi}/download', 'PembayaranController@download')->name('pembayaran.download');

    });

rental_mobil/app/Mobil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mobil extends Model
{
    protected $table = "mobil";
    protected $fillable = ["nama","no_plat","warna","tahun","harga","denda","gambar","status","merk_mobil_id"];
    public $timestamps = false;

    public function merk()
    {
        return $this->belongsTo('App\Merk', 'merk_mobil_id');
    }
}

rental_mobil/app/Http/Controllers/Admin/MobilController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB;
use App\Mobil;
use App\Merk;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\File;
class MobilController extends Controller
{
    
    public function index(Request $request)
    {
       $mobil = Mobil::select('id','nama','no_plat', 'harga', 'gambar','merk_mobil_id')->with('merk');
        if($request->ajax()){
            return DataTables::of($mobil)
                ->addIndexColumn()
                ->addColumn('action', 'admin.pages.mobil.action')
                ->addColumn('gambar', function($mobil){
                    $url = asset('uploads/'. $mobil->gambar);
                    return '<img src="'.$url.'" border="0" width="100" class="img-rounded" align="center" />';
                })
                ->rawColumns(['action', 'gambar'])
                ->make(true);
        }
        return view('admin.pages.mobil.index');
    }

    public function create()
    {
        $merk = Merk::all();
        return view('admin.pages.mobil.create',compact('merk'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'no_plat' => 'required',
            'warna' => 'required',
            'tahun' => 'required|numeric',
            'harga' => 'required|numeric',
            'denda' => 'required|numeric',
            'gambar' => 'max:500|mimes:jpeg,jpg,png',
            'status' =>  'required|in:0,1',
            'merk_mobil_id' => 'required|numeric',
        ]);
        $gambar = null;
        if($request->hasFile('gambar')){
            $gambar = $request->file('gambar')->store('photo_mobil', 'public');
        }
        Mobil::create([
            'nama' => $request->nama,
            'no_plat' => $request->no_plat,
            'warna' => $request->warna,
            'tahun' => $request->tahun,
            'harga' => $request->harga,
            'denda' => $request->denda,
            'gambar' => $gambar,
            'status' =>  $request->status,
            'merk_mobil_id' => $request->merk_mobil_id,
        ]);
      
        return redirect()->route('admin.mobil.index')->with('notif', 'Berhasil tambah mobil');
    }

    public function show($id)
    {
        $mobil = DB::table('mobil')
        ->join('merk_mobil','mobil.merk_mobil_id','=','merk_mobil.id')
        ->where('mobil.id',$id)->first();
        return view('admin.pages.mobil.details',compact('mobil'));
    }

    public function edit($id)
    {
    
        $mobil = Mobil::where('id',$id)->first();
        $merk = Merk::all();
        return view('admin.pages.mobil.edit',compact('mobil','merk'));
    }

    public function update(Request $request, $id)
    {   
        $gambar = Mobil::select('gambar')->findOrFail($id);
       
        $request->validate([
            'nama' => 'required',
            'no_plat' => 'required',
            'warna' => 'required',
            'tahun' => 'required|numeric',
            'harga' => 'required|numeric',
            'denda' => 'required|numeric',
            'gambar' => 'max:500|mimes:jpeg,jpg,png',
            'status' =>  'required|in:0,1',
            'merk_mobil_id' => 'required|numeric',
        ]);
        $data = $request->except('_token', '_method');
        if($request->file('gambar')){
            File::delete(public_path('uploads/'. $gambar->gambar));
            $data['gambar'] = $request->file('gambar')->store('photo_mobil', 'public');
        }else{
            unset($data['gambar']);
        }
        Mobil::where('id',$id)->update($data);
        return redirect()->route('admin.mobil.index')->with('notif', 'Berhasil edit mobil');
    }

    public function destroy($id)
    {
        $mobil = Mobil::findOrFail($id);
        if($mobil->gambar){
            File::delete(public_path('uploads/'. $mobil->gambar));
        }
        $mobil->delete();
        return redirect()->route('admin.mobil.index')->with('notif', 'Berhasil hapus mobil');
    }
}

rental_mobil/resources/views/admin/pages/mobil/action.blade.php
<a href="{{route('admin.mobil.show', $id)}}" class="btn btn-sm btn-primary"><i class="fas fa-eye"></i></a>
<a href="{{route('admin.mobil.edit', $id)}}" class="btn btn-sm btn-warning"><i class="fas fa-pen"></i></a>
<a href="{{route('admin.mobil.destroy', $id)}}" class="btn btn-sm btn-danger" id="delete-{{$id}}"><i class="fas fa-trash"></i></a>
<script>
    $('a#delete-{{$id}}').on('click', function(e){
        e.preventDefault()
        let href = $(this).attr('href')
        Swal.fire({
            title: 'Apakah anda ingin menghapus?',
            text: 'Data akan dihapus permanen',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
            if (result.value) {
                document.getElementById('deleteForm').action = href
                document.getElementById('deleteForm').submit()
            }
            })
    })
</script>

rental_mobil/resources/views/admin/pages/mobil/create.blade.php
@extends('admin.layouts.master')

@section('title')
    Form Mobil
@endsection

@section('content')
<div class="card">
    <div class="card-header">
        <h4>Masukkan Data-Data Yang Diperlukan</h4>
    </div>
    <div class="card-body">
        <form method="POST" action="{{ route('admin.mobil.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label>Nama mobil</label>
                <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{old('nama')}}">
                @error('nama')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label>Masukkan Merk Mobil</label>
                <select class="form-control @error('merk_mobil_id') is-invalid @enderror" name="merk_mobil_id">
                    <option selected="true" disabled="disabled">--Merk Mobil--</option>
                    @foreach ($merk as $m) 
                    <option value="{{ $m->id }}">{{ $m->nama }}</option>
                    @endforeach
                </select>
                @error('merk_mobil_id')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
                <button class="btn btn-primary mt-3" data-toggle="modal" data-target="#modalmobil" type="button">Tambah Merk Mobil</button>

            </div>
            <div class="form-group">
                <label>Masukkan Plat Nomor Mobil</label>
                <input type="text" class="form-control @error('no_plat') is-invalid @enderror" name="no_plat" id="no_plat" value="{{old('no_plat')}}">
                @error('no_plat')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label>Masukkan Warna Mobil</label>
                <input type="text" class="form-control @error('warna') is-invalid @enderror" name="warna" id="warna" value="{{old('warna')}}">
                @error('warna')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label>Masukkan Tahun Mobil</label>
                <input type="number" class="form-control @error('tahun') is-invalid @enderror" name="tahun" id="tahun" value="{{old('tahun')}}">
                @error('tahun')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label>Masukkan Harga Mobil</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            Rp
                        </div>
                    </div>
                    <input type="number" class="form-control @error('harga') is-invalid @enderror" name="harga" id="harga" value="{{old('harga')}}">
                    @error('harga')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
            <div class="form-group">
                <label>Masukkan Denda</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            Rp
                        </div>
                    </div>
                    <input type="number" class="form-control @error('denda') is-invalid @enderror" name="denda" id="denda" value="{{old('denda')}}">
                    @error('denda')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
            <div class="form-group">
                <label>Masukkan Gambar Mobil</label>
                <input class="form-control @error('gambar') is-invalid @enderror" type="file" name="gambar" id="denda">
                @error('gambar')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label>Status Mobil</label>
                <select class="form-control" name="status" id="status">
                    <option selected="true" disabled="disabled">--status--</option>
                    <option value="0">Tersedia</option>
                    <option value="1">Tidak Tersedia</option>
                </select>
                @error('status')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="form-group mb-0">
                <button type="submit" class="btn btn-primary">Tambah</button>
            </div>
        </form>
    </div>
</div>
@endsection

rental_mobil/resources/views/admin/pages/mobil/details.blade.php
@extends('admin.layouts.master')

@section('title')
    Detail Mobil
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
        </div>
        <div class="card">
            <div class="card-body">
                <div class=" ">
                    <div data-crop-image="285" style="overflow: hidden; position: relative; height: 285px;">
                        <img class="d-block img-fluid" height="500px" width="500px"
                            src="{{ asset('uploads/'. $mobil->gambar) }} ">
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <h3>{{$mobil->nama}}( {{$mobil->no_plat}} )</h3>
            <p>Mobil Tahun {{$mobil->tahun}} berwarna {{$mobil->warna}} Masih {{$mobil->status}} <br>
            Disewakan dengan harga Rp.{{$mobil->harga}} saja perharinya <br>
            Langsung Hubungi Contact Yang tertera
            </p>
            
        </div>
    </div>
@endsection

rental_mobil/resources/views/admin/pages/mobil/edit.blade.php
@extends('admin.layouts.master')

@section('title')
    Form Edit Mobil
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
            <h4>Masukkan Data-Data Yang Diubah</h4>
        </div>
        <div class="card-body">
            <form method="POST" action="/admin/mobil/{{$mobil->id}}" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="form-group">
                    <label>Nama mobil</label>
                    <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{old('nama') ?? $mobil->nama}}">
                    @error('nama')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Masukkan Merk Mobil</label>
                    <select class="form-control @error('merk_mobil_id') is-invalid @enderror" name="merk_mobil_id" id="merk_mobil_id">
                        @foreach ($merk as $value) { 
                            <option value="{{ $value->id }}">{{ $value->nama }}</option>
                        }
                        @endforeach 
                    </select>
                    @error('merk_mobil')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    <button class="btn btn-primary mt-3" data-toggle="modal" data-target="#modalmobil" type="button">Tambah Merk Mobil</button>

                </div>
                <div class="form-group">
                    <label>Masukkan Plat Nomor Mobil</label>
                    <input type="text" class="form-control @error('no_plat') is-invalid @enderror" name="no_plat" id="no_plat" value="{{ old('no_plat') ?? $mobil->no_plat}}">
                    @error('no_plat')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Masukkan Warna Mobil</label>
                    <input type="text" class="form-control @error('warna') is-invalid @enderror" name="warna" id="warna" value="{{ old('warna') ?? $mobil->warna}}">
                    @error('warna')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Masukkan Tahun Mobil</label>
                    <input type="text" class="form-control @error('tahun') is-invalid @enderror" name="tahun" id="tahun" value="{{ old('tahun') ?? $mobil->tahun}}">
                    @error('tahun')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Masukkan Harga Mobil</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                Rp
                            </div>
                        </div>
                        <input type="text" class="form-control @error('harga') is-invalid @enderror" name="harga" id="harga" value="{{ old('harga') ?? $mobil->harga}}">
                        @error('harga')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <label>Masukkan Denda</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                Rp
                            </div>
                        </div>
                        <input type="text" class="form-control @error('denda') is-invalid @enderror" name="denda" id="denda" value="{{ old('denda') ?? $mobil->denda}}">
                        @error('denda')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <label>Masukkan Gambar Mobil</label>
                    <br>
                    <img src="{{asset('uploads/'. $mobil->gambar)}}" class="mb-3" style="width:100px;" alt="">
                    <input class="form-control" type="file" name="gambar" id="denda">
                    @error('gambar')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Status Mobil</label>
                    <select class="form-control @error('status') is-invalid @enderror" name="status" id="status">
                        <option value="0">Tersedia</option>
                        <option value="1">Tidak Tersedia</option>
                    </select>
                    @error('status')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group mb-0">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
@endsection

rental_mobil/resources/views/admin/pages/mobil/index.blade.php
@extends('admin.layouts.master')

@section('title')
    Daftar Mobil
@endsection

@section('content')
<div class="card">
    <div class="card-header">
        <a href="{{ route('admin.mobil.create') }}" class="btn btn-primary">Tambah Daftar Mobil</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="table-mobil" class="table">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Nama</th>
                        <th>Merk</th>
                        <th>No Plat</th>
                        <th>Harga</th>
                        <th>Gambar</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<form action="" method="POST" id="deleteForm" style="display: none;">
    @csrf
    @method('DELETE')
</form>
@endsection
@push('addon-script')
@include('admin.partial.notification')
<script>
    $(function(){
        $('#table-mobil').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('admin.mobil.index') }}",
            columns: [
                {data: 'DT_RowIndex', orderable: false, searchable: false},
                {data: 'nama', name: 'nama'},
                {data: 'merk.nama', name: 'merk.nama'},
                {data: 'no_plat', name: 'no_plat'},
                {data: 'harga', name: 'harga'},
                {data: 'gambar', name: 'gambar'},
                {data: 'action', name: 'action'}
            ],
        });
    })
</script>
@endpush

rental_mobil/resources/views/admin/pages/mobil/show.blade.php
@extends('admin.layouts.master')

@section('title')
    Daftar Merk Mobil
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
            <a href="{{ route('admin.merk.index') }}" class="btn btn-primary" data-toggle="modal"
                data-target="#modalmerk">Tambah Merk Mobil</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-md">
                    <tbody>
                        @if ($merk->isNotEmpty())
                            
                        <tr>
                            <th>No. </th>
                            <th>Nama</th>
                            <th>Actions</th>
                        </tr>
                        @foreach ($merk as $key => $value)
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td>{{ $value->nama }}</td>
                                    <td><a class="btn"><form action="/admin/merk/{{$value->id}}" method="post">
                                        @csrf
                                        @method('delete')
                                        <input type="submit" value="Hapus" class="btn btn-danger">
                                      </form></a></td>
                                </tr>

                            @endforeach
                        @else
                            <tr colspan="3">
                                <td>No data</td>
                            </tr>
                    </tbody>
                    @endif

                </table>
            </div>
        </div>
        <div class="card-footer text-right">
            <nav class="d-inline-block">
                <ul class="pagination mb-0">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1"><i class="fas fa-chevron-left"></i></a>
                    </li>
                    <li class="page-item active"><a class="page-link" href="#">1 <span
                                class="sr-only">(current)</span></a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">2</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#"><i class="fas fa-chevron-right"></i></a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
@endsection